### ISSUE TITLE
Progress texture Orientation

### ISSUE THREAD

**Issue by Zidras** [Bunny67/WeakAuras-WotLK#11]
Having strange orientations on progress textures.
Example: Circle Clockwise:

![image](https://user-images.githubusercontent.com/10605951/83944330-b2b39e80-a7fa-11ea-8e41-4d1cf5382a7e.png)

What It should happen:
![image](https://user-images.githubusercontent.com/10605951/83944351-d676e480-a7fa-11ea-9e0f-5738cb7dd644.png)

**Comment by Bunny67** [comment]
At the moment, "Progress Texture" does not work as it should, I do not know when I will fix it

**Comment by SorenMills** [comment]
FeelsBadMan

**Comment by Zidras** [comment]
This is fixed. 
(if anyone has the quadrant lines, disable multisampling in video options)
