### ISSUE TITLE
Trigger= Statut, Cooldown progress spell, Action usable

### ISSUE THREAD

**Issue by Solosszer** [Bunny67/WeakAuras-WotLK#13]
In the "statut" in "trigger", some tools are not working, 
I can't track a "cooldown progress spell", the trigger don't work.
Same for the action usable, i can't only track when i inverse the trigger..

Pastebin for the action usable not working: https://pastebin.com/RYFLbq4y
Pastebin for the action usable when i inverse the trigger who work: https://pastebin.com/J46GCZix
Pastebin for the Spell cooldown not working: https://pastebin.com/nMx1KzDu

**Comment by Bunny67** [comment]
should work now

**Comment by Solosszer** [comment]
Yes i tried, work fine, thx you!
