### ISSUE TITLE
Chat Link receiving display information

### ISSUE THREAD

**Issue by mwoodtech** [Bunny67/WeakAuras-WotLK#14]
When clicking on a chat link from a user with old WeakAuras an error occurs.  This issue does not happen when both users are using this version of WeakAuras.

![WA chat link from  mop to bfa](https://user-images.githubusercontent.com/66507786/83954495-89950d00-a7fe-11ea-891c-2d0df6ff9b85.jpg)

SnD WA string:
```
dqJRbaqArNxv6sqGBbP6AeY6Hq9Ais7ckmBQCBPYoju7fTBs2pb9tiL)sk)Msddk14KcoiuYHPQjRIfcjzPsjhJuTCv1ILs9uLhd8CqtuvmvkwMk10LCriORcHCzHRtuBeIYMLQEgu02Lc9riI5cv9zImAiQgmuz4srttL8nirNKaNdsyBqsn1PHl5eOQ437bbEbaRcIhR2PlRxTwwj5qBUeepji4GC3yGngnW1XD4o0Wv)usk(0WP8DbKgkwNBUeecX5vhH4EsqWIdidlBNgYZtWvzxCyX5S(dnCYWqd48qirf336cA46KDvsdlwCaNhcPHdMkjxW1cnKGieYIfxVvvlrCqX3xCNe205Fx5bifYHGMC)qkTkZBZGlbwfxE4M6Htj3z(PKu8HuSo3lA99WOiYqhLIUrXLimBqK(nQVVWuN9OFjIZdQ0QG0Wbl)VOH7y1Gwz1HTzXIfNNgU5sqieNxDeI7jbbNavf)EpiWlayvq8y1oDz9Q1YkjhAZLG4jbblUgPy9lDSzrc
```

**Comment by Bunny67** [comment]
This can be done, but if there is a conflict in the old aura with the new one, then the addon will most likely break

**Comment by Bunny67** [comment]
https://github.com/Bunny67/WeakAuras-WotLK/blob/master/WeakAuras/Transmission.lua#L652-L653

**Comment by Bunny67** [comment]
Old string will not be supported. Will be completely removed soon "Legacy Aura" trigger
