### ISSUE TITLE
Zoom display and condition

### ISSUE THREAD

**Issue by Zidras** [Bunny67/WeakAuras-WotLK#17]
Zoom functionality is applying only on the icon from the option list, not on the region itself. Is this intended?

Zoom 0%:
![image](https://user-images.githubusercontent.com/10605951/84260002-34fcd500-ab11-11ea-8e73-5e0ab75e9636.png)

Zoom 100%:
![image](https://user-images.githubusercontent.com/10605951/84260032-434af100-ab11-11ea-9926-4f347bffbd5d.png)

**Comment by Bunny67** [comment]
Zoom is not available when the skin is enabled in ElvUI

**Comment by Zidras** [comment]
Thanks for clarifying
