### ISSUE TITLE
Unit Boss

### ISSUE THREAD

**Issue by Zidras** [Bunny67/WeakAuras-WotLK#25]
#23 Unit Boss is triggering all the time, even when unit isn't a boss

**Comment by Bunny67** [comment]
```
!TsvqZPnpq0Fn9yZyiP9B6rG60W3qSPwknTZKrGWEnwjgjglzijh43E3vchCsU0dzgpILvpT6TVDxjgi4cMsWMQDqtPmhUBAUrBVJTfQRx8Dq6QEqRwx5wmU2ykM3awqNdcMvWgE2G)7SViyBeSc6dJKZKVdASkJwKCE05rrc2JPLLwWjsq7CtTPbXLmW)n0VEUF9cA1rq0LQ1ig0w26QmnPBDy8Sbxp1lAsDoU9CJsJBmjoHhNjynWAen)PTihvyW6GDzJCdeCZMKfhNGBK3fyM1jBCHBOuPv2QGnAg8giJrmMiOPUWSxhxSgeRoEjOFxJA9Am3dPh)fhKzRfsWRNGjBBKA0(ioMxwpSCUzpcfVgyhqPZvGS2vHeRDL3dk8LQhrUppE2m0nvEMwCuu6aXAl9GwmzeJVGXhLr3nLdSvglwX6Uy0HZlfeBgI1oyfE0G6Cv8S5xEZmctR(uoe0auX2b8GZRnfGi5ZdIckf2)OL1)QR6p8Bc2ZgZgFL6ba2oc5CUltIAojBsTAdzR7l)mqAbu4a9Am5XoJJ0uB04Absw6elcoTaQ8Oe4pe)eoKnBKk9hy4EPL4dkGKEHtmoW6oSCCQ1EyzOkzH6Y30plR3wj9DkfGv6ORW32vs9ZivKUWUTueJUpBEXK60SR)FQKqJIEWydsMFUOx3j8OBHTsITY)U3mL3nTiyFY(kut6n7g5NDJ8ZUrNMDdOpLdJUHNE0ln9q178BvfuF9iAAkSf2Ycfb3jF9IU51)8wsDFR1PkFQ3KUXHAb3Z1K0K4UIbMSHeWFS)HNCcSWqm(Yg1Zhw(ZwzbjShwYFTs9osT30uCBJCRGD7lw(n2PSQv1(j(q(3)TQPjjXzlgNY5PxNn9hxX7XbM6zCQAWWoD4DfhcuOBk9g(SPyE7BOQa6v6Gcs9DQEpAwBK(xNPjq63nT1ov3mn(2eksBwjD(x3QLw77Wyjs9gNO79Vu0W)Sdz9fdjbv83)
```
If this, then I can not reproduce

**Comment by Zidras** [comment]
`!TsvtZPnmq0Fn9yZy(Ontpcmon0bSPwkL2z6iqyVguIWIXsMeYb(T3DLGGtYLEiZ4riwTpP3(0BLOJGlykbBCLdQlL5WFhNBQS)DWkLw5oSyUSwBYFyX4T7Qn7HcMPrpbG8ncMvW6EvNRV6lc2wbRG(W9swLVXuFtTClWpSdem2OS44ebl3On1ygjD8FD9J98J9PrhITXHyt35uifWuXqpLwwAbNijcxo)8cmRtw7czuQQu2nH540quC(H2i9KAMrvHlmkoHhNjy1WAC7cKuHfnbhfHkP(xqTfxcj538KYigs8VQuToCo5gJUW8yvCXAqS6eCmhxTA9AeCOm5VeWp1FqYMAzxbRXcXpH1dBhO1JliSWEGy3TGu7q1TcfWtAqdvvSvglQ42aGtRyBw5HnRgkvpHA9S4jtchIprvXjQWUUFVUrTHWAk9qwmAaJVGXhKXdapFWeQHAJP44YzMhXAabxaRqybj72bztV5UjbcEPo9ApDtTh4HGtnfGi5ZD8hVSsTvsxJTVfzG0cOwbvRXshnfNeRktfowGKIqSie0cOyJ1Lhe)sE4MVvQQ(a3UxCwFqBiULpBmB9oYhay3a8ok3LrGjtKZKV)SXRxuVimlf2v5aR74YHPw7XLbNGf0LVXll172i9xzpQkio(1(i)PMqK2sxyPgA7IUpBwXiDA20FqgE6e9wy0xK5BiAzEHNClSBKOt)3TAM8HPbb7t2xL1OwT4r(w8iFlE0Lw8q2xkGb3XtpfLA0iVr(CFjWgqnEHLqNkum)sLf6N)ZBj19nwNQ8qRwCJt6aUNRjPjXNV4WInuaEy)hVmfyHHy8n1QNpU8NnYcsypUK)AL6DK6rtDX8A5obB(lZ8lSxzvR0G)DdF93(rQXjjXzlgMY5PtZg)9B5T4at9m2q1P7zD4DxousbNx6D8jJX62B(2aQ1BCbfK8OQwVZQns)Z3KLK(DBJ2Po3oNRLw77IAjA8MG(3iSsh1sq2k8)7rQ2VlPII)9`

**Comment by Bunny67** [comment]
in retail also

**Comment by Bunny67** [comment]
Maybe it's used like this
```
!TwvxVPooq0Fn7J9Q8b9dEzLau4wwrtyJtx2R0vgmjoeFVH4iBhG2h43(oJnusBFzFOsrgNjJhFMZCMbQpnJseuYSgdxvYY5)CwUSr)ZrBe1cZlRwYu1Y8FVA2UwLCpVGi7QNZ55vuIMsc(M)9F7wkzhLuGpqSoikmv047gaHfIeDmLCmPSuZn0P3CB4Gh8cU3FqO)WB9FiGwEZGqkjxwlvWHJ9Tpb21q76aC1qjSotLuL0Aea6axbtVCjS35ho8U79g(q4aVWGWqmQW1ZAYHJSqkAaNNefNfLsjk(wiczV0YpJpYRs5oAShL8BoVDKULNBszW1q3qjDciT8(v6IIj1jPp9xiuL1fYdnrfB5OhS8liIOnmLXbnrJ48UsyRUYUhEZOeB3YvAxUM9Mb7wlMyDkwaqL8nDLLoy(4O0NM(8CanA(3vYU2v5YoiNg78gqCDTO4Cmj3pimWdVRT9CLaPhFph39iNvdfisdBh)mrcXn6iKiemsZkWa3HjazJudfzTZ8zN1DBSrIa4tCKswnzejBfjBuAgYo72iA4pjlaCRRKhEuSTIR7DSfkU9yKfrZN7sGlibr)4APS406fYdaP8(KiPLRygqNq(tlOBUYDwUfRe75zoJweeFJVLjkvWnaunZWSxIa16nS6)bQeqXdeCdTcmPLsBe7WYFt)s65ItJSbw5mngnEZwuOdY3cijWtSY5LMd6kGUSoMD9Gas2XenFHH7nX1xuarLli4nqf706XjA9P1oHGrMV)czf6f6bYjwDBLJoD9ztrs2fnYK0OOy8IQl)q7hCZLITxAsWyA7Ia1rQTXSxNb)OzLUIbnB)75gDSj1AgxOK)q)oVM0BiINDiINDiI31HioVVIQrpNLC2kw(X6E(s78lYiuo4(eOx5flVowZLV)4JG6xDAJO8LEJAKgMHNzXACsC0LQeKSUeWES)hZ(COqIiEQs86P1)DhRavZNwN9EM6tG6GuvSuXAPKLVTZ(H9cTytnhv8U8V)WYzXXrPRgNKLL8u6SV)ywpmqeVcDw(bx4HpvCqNC6GKNZMpdYBRWQIdJcmoge1FIEtYRLm7)DGdFXF31vBex6RZRzA9NSQry8bJgCUPMzq5okRG33dqDqaYI0)7d
```

**Comment by Zidras** [comment]
You might be totally right. Can't really test it on boss right now but that makes perfect sense to me. Closing this. Ty for looking into it a second time.
