### ISSUE TITLE
Specific unit boss1 aura triggering even when unit is dead

### ISSUE THREAD

**Issue by Zidras** [Bunny67/WeakAuras-WotLK#28]
This aura is triggering with boss1 even when unit does not exist (made sure I had **Show On > Aura Found** and "S**how if Unit Does Not Exist**" is not ticked).
Original aura had 3 trigggers but I duped it and narrowed it to just one trigger after a boss fight:

```
!Tw13ZPnoq4)AUzsFiDmgcKmZ1BgAc5sYqboKZL7M0kqyV2OwJKhjzi0h4V9BxjtWP9L7HoW4FiTA3V9B)218o8eotYz3RCGjxKcF((uTY(zwfuwU4oD5(fZLfRDGU2EBTzpNz5S433zW7VGZ2Wzz0F0foD6wWyLAfFs3OUrrC2ltZZTGJF7LxErVbD719IUdgm4Qbd45N3Rh6iOmFMwQCC21JMKmAoNjQDR1MPvo0pw0T4wLAHpa1wyHcWyWxHrtuc45WLTsvrjWNe3hHtDPtIlsV8r8S4PTvqkz2XT8lMwkS2whMnB44H3C)KtM96khDJ87qB3WQeg3ECxw12k6Mdu(B7qyTpxUfO3Y1OrBe(DuAf04ncb6sTHqAh))y)1U(R9OROj7pYEN3VFC)Ux2V3vd60p(QOEe9HKVqLIC1pqGgOaPUK9vywjXczZveaFdGQHeD4Mlq6LyrCNCzrGMt16Ym9o1OScG2tKESgWSomzdwjvYMNYXhTRpYOoJSOal)Huk51fOhnaktUWxa)tJUUArQUgHmcPncx6AWYwR3nfrQ1FFigyK(y26vy1w5MzGC5lCgB2OXJdfuzUm9rcjSvARTtJJA8ldFV4uCMwbgHdjB2FGOYZlIAJi(nh6KrF4dCMpSC2DGO0TgXTpsBGnRW8XFyl1BiZAYwwCuNlVWRsAGmRo3d5fxpKLSGLmCEIh4LL3N1OQrYy0lihZcRsSbYtNWXVJ4idwHokulVB48pD7Jy(ReBGgF0kl5SiVxvN4DFDjtA)ATQHrfkS7nT260BscMnwxitXAP3eT6SMt)UdpCyz4NbC1g1HLn78C8xo8aOYc6JTqJF(KodBbpVtuqJGtsuIY)(44G4R4SVR1B4tI8D4AkBfk5gshQARWAkq(EfgiSaQJavbwfWMdwgs90jweSYcO(f5tVHjNoivSes1Vq39Qw)xKdjscPWNNjkfzs1xoS8zAqlE)HAS9BdkHoSuNFy5yAY7HLNPaiZsfJTsy37oSevV7Kzuy7JZrfLvRfELygyfocf(w4CdQvqekCHDRPGE2nMYpQ2)xFlQGkv0mBVXO2DUF2rREy4f3c7Abow4FAggrvq)Y0fo73OEJjyuEJXx3A4wKF4wKF4w0PHBbRpn)F4JjtBwLeiKYi9jFgYgscMWwytfK9uRe3pb8F)rS9vuIlZ33AOO2HusIhYtMoz0X6iMZH8WFS)hZKdOqtiE0lvgWA3j2)MC)NaZoTj7jJOIZE61N8BSvALRkHWhpO8U948PpIaFrY0zTIjJ(g0KoXhZ7FQMqgf0z4XhFpMNEP2AGurbgJuKYwFC94u)qhj51BjrtWlSRNpA0eYSTyC7ftua))c
```

Image: example where rot had been killed (and I'm standing near Quarter entrance):
![image](https://user-images.githubusercontent.com/10605951/85082518-12308780-b1c7-11ea-8ac7-412f67ec429a.png)

Stream with timestamp where I was trying some troubleshooting with the triggers:
https://www.twitch.tv/videos/654786645?t=1h15m22s

**Comment by Zidras** [comment]
I'm afraid I'm still able to reproduce the issue. Even though the unit name no longer shows, the aura still triggers even when the unit does not exist.

In this test example, aura "on show" = Aura missing and "show if unit does not exist" unchecked.
https://streamable.com/e5m727

```!Tw1xVTTnq8pndO7Huij)NKaSmaNuNLm4i7AQSSH2rBAPtYSvMuGKYoUp4p77okjBN2x2dfqqI64Dh)D397oYd5jCMKZEu5atUif(8JPAL9ZSkOSCXd6Y9lMllw7aDT9(AZEoZYzrVp8Y3pGZ2Wzz0d6crTBT2mTYjrRrbooB)08Cl443FXv9g2pkOxy)WHxh0RFip)I(drBuPOnZ0sfQ9DJJtgpNZs16Ym9o14ScGVcvkTZLmRtyCn(oxQK21nRXLnsX1oJSOamK6X(qRvaT0aiEruxBH)WORRwKQRXt(wmoeU01GLTwVBQcph)3NKwRuvWzkXgOnKSvqQmxM(mDKSvARnKZkoZzSG38)0kWiCAdN97iu2xbuIYiIqpvVc2ckhRopx(kNT4UrSKfSKrZrK63HZEaeLU1TWR7acpz7md4TLnB8KjyDawHolXFkpmA(t3)8epIllFmRf)yOp(vmJYAKsXoMvoHYF7Mga6TsM1MgzrbHxnWBVpU3aBwHP0ZX1jxCZnnkEkX7lmzs7xQvyTClLduipkT260BsAuBIUqMYznL7TqR0N0zap(IWGMYmYqvIY)clViJGhhDnN9vaQgrvf3CbYticJfkZ)oovgyfomSCEgfM(MdfTKQwwc8QBHDTajE)DlRnoOvm9IZ(fk0JrMWBu(oDP204fu)4i)7E(39jHUoTpHPrpNmTvk2ZOXCOm9fzgvNhH)3UfwxHSgXXd731Q8pFp2(cMdL57pfPgTdJYepKJNgpUJ1HXCtC4nl9myh6HDOh2HFhSZ1eIh)ALbS2DI9Vj2)bWStBYEXiQ4SxoUYVXwPvUQei2wtCFEF)0NrGViz6SZotM8ByDpmQlU)HAcPudrhnFYJyC6jzRbAuvtgRul8dMqk)cf2UyOsVtusDw0SeS1gHuCeohAtDPtsPd8NBB8erPi162YlmTuyTNzmB2OjJ(WJXNu7OKo3qbYzUHvHtW2tjcLw1Mqu(p7qCTpN6oW)Y1OwBe(DQ2w16nh1Ss82MixIZPPeKKOq4YZgqYaHfWrFGQGiq96yb(dLLrDcOflAPga6iSv3BuYj9OgDHu9t0DhhA)tYHKlnylj6jHt4Nu9nTEJNMq9w(eRoDB3aJEb9cWTK4DwFAMOuKjv)7HLFIUKd)(N14noBWYWHL68dlNquPdlFNcGm7HLgyRe29RhwEKuEpD0n4HD38XJrAGOSADdo2DQ19)rZggG5YIUBZi86hu96XlqVmiyWvddV66brbxEDVb4fOdqGutHY7(GP8w1(p(1GcVNYKNDhC3TPuQWtyiQeBlEU9JOJM)Fp```

**Comment by Bunny67** [comment]
in retail same bug :(

**Comment by Zidras** [comment]
Since it also happens on retail, I can workaround this by adding another trigger to check some unit characteristic. Thanks for checking.
