### ISSUE TITLE
Desaturate via Conditions not applying every time

### ISSUE THREAD

**Issue by Zidras** [Bunny67/WeakAuras-WotLK#32]
I noticed that when trying to either apply or remove desaturation using conditions, sometimes they didn't work. I didn't do extensive testing on this to pinpoint how to reproduce this but I've seen it happen on my system and another person's system.

(I'll edit this when I have the chance to properly troubleshoot and create test auras if needed)

**Comment by Bunny67** [comment]
I know about this problem, at the moment I don't know how to fix it

**Comment by Zidras** [comment]
I'd like to add on this the following: I have found a way to reproduce this bug everytime with range check triggers. I also have no idea where to look in the code for this, but I'm leaving this finding here nonetheless, should it be helpful in the future for bug catching.

**Comment by Zidras** [comment]
Closed by https://github.com/Bunny67/WeakAuras-WotLK/commit/5e69aa3ebec5e7d1a8b8bd3a2f68af725764307f
