### ISSUE TITLE
TSU Trigger WA's do not load automatically

### ISSUE THREAD

**Issue by Isdisbase** [Bunny67/WeakAuras-WotLK#35]
I have the Problem, that my TSU Trigger WA's in a Dynmaic Group do not load/trigger until i open WA and open the trigger once.

It happens after first login or after reloads.

**Comment by Bunny67** [comment]
please give example wa, string

**Comment by Isdisbase** [comment]
!TJ1wtTnou4)lmZodD2sMCdO8apKabi00KSroLUlT2wXw2rloszLLbs7w)BFp6i7KqkxA6WJ7eMG8XhDUPpD0NIBnxhxsQlPELAhw5DUKzUKqZFG0yL8oxYPdUQVlzIufYuTPb3eQKZDjTt4F9RuvyUVJuMO5GO7hefLY0UNDyJAVRrZJoSz1JoOzZQvDJ2R5bUKfLVF)dQFe86AnpSr1QnASV59hAChp0zXCMlz0PLo8ezIubXs)AU9R62Vo(Dd87MgHAxceKK50aM5rcnqZLIumN0uLggaQWf8IrrWW0P4y4jTIhhZuPwh4SuGzyiBswuKnEUOtVHNnUh8E8rAMIwhCWCwss3WuRLtZMWULj0eyw87DjEN0I44rCAncmwMjaiZtOlaJte0zSIzHtbCaJMONUYidvm0iKHD61ZOxMyvOPTbFGmjBMyvQROH8SuOgbfCcvWNrnLI1RefHVqkGVz0ugKVmrm4yOKscHSYmdpRwPSaPasourNvte88mkx8kAULRjVsgemjnHhlCjN0PVtNrybaRDaSXuIhXIlajGQjskc2ZszEbj00u3j4sBGr4SmaAxIwSVDtPP8VY2uiiEsXoL1bW1qaCneaxdbWvRSpgU4Qfd9CanXUEA3ayKzh1jmgYrY)KrvSC)ZYssY9VAkhMgrHjKTieUaGx8ayVB28YPsmXyFdKvcaHIcmvemvQgk5gayzLcEGPe0Kpc7kmON(1pYunqmwDdMta1sH(myFgKwKrToT7ycylvqVYvQdQw62I97qIcBz0GZgmxVQWRLb3w6LgvByqTCOZZ1NIB8(sUFV2LgQRaTtnBpIR4HghTFzkCMc2pztEYjJ60b6wfzebOhQMItlZy53hg9hHNOJVu9jmtI4XfBDzjrf1bNbdbibFgSD14adeJVwmRKA7Ukdscqm9qnNGOJLnrk7Z1V((prvoaAzgkVtGlPWcmh8JB7NVFKf1hKLQLZEHUn)unv2ONuPHJYeyl0DPjjWsTML(2CFC6V1dgb2Qd(am88XDp9TPYmvaRpuUH3hIIY9dzP6crGE22KLJq5vQu5n5xM7B)WJkCrU)XhN7VZjd(q7woE9gCUxNpcLmVX9pRBpOY150DY9PIWvXrXmWuYR14rT8AnCyVUOI6PmXkNSUZmnW9yIBRGru61fHiG5Y)xWCcEYtn71TcKNM8D9jzJTLLKJpEmuKnJ2DhBHEN38swE5NxuJej0Ri3)g2cOkuemvQuKlVIoWCCfS6POIBG)zWQO)oNPjOVerYDl86BEnC7sK31qQ9f0xBksQY9)233wtvjykveZcrtQvzST2aPtL39Rp75kzSILMA6vHwzhnFglCNT2qlxdWbB7Slpi1wzFQTcBRvz3pNBTRdKuLieZ4Dbm)V)k6jGntmd3vzX9fnB2A7aNjjVGhY(1xqfBFm8YAOy6mL4NnIEAnyMErVKYgLU8bpyLGF2KIR9mIs(xM6q28qdVfsWuwWnlp4zt(TajTNPL(Jt1(r48IK7VL5yf(bziWjzVAvTe8FeAl3WyZBzyYPhzWLi7QvN0xEwmS0r1MDew6xRZoS4my29AV0Pu4a7pvEY(bfInF5s(nXd065VZcgVwTxfmTg7mOqQbvAOUhyP5qAbpx8k40Bwj7NdAwYT4pldQQfQ93WYepAXQuezTWCWyT)G(DkjtajRnbSogT2N20Abplb2AlZMiPjrg6K7dXvAUFFQcV(4AfMLrATAfYVdO3DLIcevVA5i8f3Yt5taIWTFqWvuTgmgslVrDp)cN1CULKBTdkRl)qMyuYcYad0Rluhqu1ugpEkOwJ6RUmWJY)hVHGC2eQ2ewB1TbwNGos2B5LLnr3D2L0g1)rcNBsK9RsGKMzogyIbW(eSO7XVLlIZ9BdXBUF9))cHjZNARGp5DgW7iCYOlVN8xVV1f3D5dVJaxykZypIFIDepY1Dc5PgkGDXv)UM(vrWTQ(S550p3AcpHRx49bAmZZU2zw5wDtbdI7z)TniHsVco8TxXMFJZCXZQ(2Qg(xV)(W11SuSQvhi3T3Epa4C53)HFZeSAElKMnRBYu3)l

**Comment by Isdisbase** [comment]
but as i said this is not only a problem with this WA i have it with basically every WA im using TSU trigger

**Comment by Bunny67** [comment]
this works for me

**Comment by Bunny67** [comment]
It may be worth finding a reason why this does not work for you

**Comment by Isdisbase** [comment]
as i said it works after you open WA but if you log in and just applie LB on targets its not working

**Comment by Bunny67** [comment]
send me all your wa, in WTF folder WeakAuras.lua

**Comment by Bunny67** [comment]
You still have problems with this?
