### ISSUE TITLE
[v2.17.12] Combat log trigger 'hide' portion cannot be selected.

### ISSUE THREAD

**Issue by CristenPerret** [Bunny67/WeakAuras-WotLK#37]
When making a Trigger: Trigger > Event > Combat log > [Hide: Duration] 
The dropdown menu populates, 'Timed' can be clicked but wont select.

Importing weakauras that definitely had this section populated no longer is.

Sorry if the new changes already fixed, had past issues updating losing crucial WAs' so not risking downloading every update constantly. Appreciate the effort putting into this so much!

**Comment by Bunny67** [comment]
Should have been fixed in recent changes

**Comment by Bunny67** [comment]
You still have problems with this?

**Comment by CristenPerret** [comment]
This was fixed by one of the updates, sorry for not closing!
Great work with all the Addons!
