### ISSUE TITLE
Desaturate Reset

### ISSUE THREAD

**Issue by Merfinx** [Bunny67/WeakAuras-WotLK#4]
После /reload эффект обесцвечивания (Desaturate) сбрасывается. Точнее он есть, но при отображении Ауры аддон его игнорирует и отображает без.

Пруф: https://clips.twitch.tv/WildUglyShieldCorgiDerp

**Comment by Bunny67** [comment]
Гляну.

Пиксельную обводку лучше не юзать :) Она кривая, и врятли будет фиксится, так как на личе не хватает апи, для такой реализации как на оффе
