### ISSUE TITLE
please make EXRT for WotLK.

### ISSUE THREAD

**Issue by coolaken** [Bunny67/WeakAuras-WotLK#40]
I dont know how to show you my gratitude,but I really appriciate of what you have done to our World.

**Comment by Bunny67** [comment]
If you mean addon, it doesn't make sense to move it to WotLK, as more than half of the modules are either irrelevant or will not be implemented because of lack of api.

**Comment by coolaken** [comment]
Exorsus Raid Tools have the classic version,is it possible.

**Comment by Bunny67** [comment]
in classic API from retail

**Comment by ajseward** [comment]
@coolaken RaidAssist might have what you're looking for in exrt. I've backported a good amount of it here

https://github.com/ajseward/RaidAssist_WotLK/ 

the original addon is here if you want to see the features. 

https://www.curseforge.com/wow/addons/raid-assist
