### ISSUE TITLE
Some servers block characters used by LibDeflate's EncodeForWowAddonChannel

### ISSUE THREAD

**Issue by ajseward** [Bunny67/WeakAuras-WotLK#41]
## Describe the bug
Linking weakauras to other players usually does not work because of this.
I assume the server is blocking some of the characters used for compression, causing parts of the comm message to never be sent.

**Do you have an error log of what happened?**
I do not but I have experienced the issue with other addons. 

### To Reproduce
The only server I know this happens on is Warmane, I'm specifically on the Forstmourne server so I'm not sure if it even exists outside this one specific server.

Play on warmane frostmourne, try and link a weakaura in chat to another player. Usually the receiving player will never complete the download.

**Which version of WeakAuras are you using?**
2.17.12

### Additional Info
I've had this issue in both RaidAssist and RCLootCouncil while backporting them. I'm not sure how reasonable it would be to swap EncodeForWowAddonChannel with EncodeForPrint since weakauras send much more data than the other 2 addons.

**Comment by Bunny67** [comment]
I think it is unlikely that it will be possible to fix it, and abandoning LibDeflate, I think it is a bad decision

**Comment by ajseward** [comment]
it would be replacing 
https://github.com/Bunny67/WeakAuras-WotLK/blob/3f0c397b28a4167017468f95433756f9bef69395/WeakAuras/Transmission.lua#L686
and 
https://github.com/Bunny67/WeakAuras-WotLK/blob/master/WeakAuras/Transmission.lua#L660

with `LibDeflate:DecodeForPrint(encoded)` and `LibDeflate:EncodeForPrint(compressed)` 


Maybe add an option somewhere to force it to use encode for print at least so warmane players can share weakauras?

**Comment by Bunny67** [comment]
Text grows 2.5 times when sent

**Comment by Bunny67** [comment]
![image](https://user-images.githubusercontent.com/5816685/88867945-88d59180-d217-11ea-9b48-2b860e335c89.png)
![image](https://user-images.githubusercontent.com/5816685/88867978-a1de4280-d217-11ea-8d1e-b34e4e891337.png)
Hmm, not 2.5. Then I'll see how I have more free time

**Comment by Bunny67** [comment]
I'll look at it again as soon as I have more free time

**Comment by ajseward** [comment]
https://github.com/Bunny67/WeakAuras-WotLK/commit/3ad99f860a6d32a50548ccd9c1fe705d50befb7d 

did fix it on warmane.
