### ISSUE TITLE
[Status] Stance/Form/Aura

### ISSUE THREAD

**Issue by Esstiven** [Bunny67/WeakAuras-WotLK#42]
Not sure If this is intended but currently Stance/Form/Aura can track Auras that are not being used by the player.

Example string:
`!WA:2!Drv0UnsnuuIkcwnGeBdqfSiXgTRu5jAirOLNZKMW2QSDZotybkfLXZ47KXcp2d2EM20hJ0kTpNh4dipZt5tOFbwv8fSFc9lGRNKuKiVe779oNRpN7XUXWM5nPnPV9XQREzAQgmnuZ3UynrKKjvJLmHjU)GZMmi4MePKtLxkgqNbz(SePiAHrXMndu6V(q12LV9HbcsoO98nZlGyTHyk1lk1W0sbZeTKuQi1fCEX(HaH3sM261GygGDekAUluFPsvwyysXD)xO8CIGE7U9JyZYm3N90sTHLa(UUexWjZb1ck2lhen7eavGWu8WqJRnThkv5T7HzFNUmUo1yfKYUkiC8GrJUpyyzkgC90(9cNmnCsVGjRDeHjQqkdzl0faNFcf5Akc4bXAMygh(efw0zifJQPTlvKQuuJOpP0ixrHye5jO(OE(GrJh(tJwwk2QFEhAFWFz9SFK9r2VY(5n7ypyvFPGYCerB)u7Nz)c7xU0HmHZQGi7tSp1(Xr2d9k2NKyWqt2G0lKu4VFV7WjiOee(RXZmcr)7(dak6Hh9etGtDYwseS8AD6zb44szgEdq0qOrHJft2hA98fsbC7o1CQBWI8hnau9cxPoMyB7NtyIH2JWpW22(D2o2U22XPmbtN9)dJsGgngiGq0kuUdGzo69OQ1Xsffut1SRH9UD7g5gt5kdCLzAIKlvE3Snv9Ut3RrJ9E32ivmnlMdr7qcq7kA1(ZsIcAnSKZB9Zzmdy9wI9DtnXzGZl9kFUKqRQ12eorR3maDhLSydHJZVdTp(nb5LCd7G3evBgQGmwchVq4u0dSh7fu)PyHQX9g174todJ57Wad11ac7XdTNgTYCjc38u3eCbArmZrVDuqbk)ZJwPQLJAz9dc2sr83Akt7S2NGsFX3CIBWMssGlC71xe6CJtFUKpFAF0csqI5S4(xlL5nSpnBLrMuTXe8GQlEcJwS)Vn(3BTR2wUIxNQqJlo6jgYEbeErg(3LmQj7vkN5c7ZZSFRN9798X5QXRBjJU(8RtM)IW8Z)1FSNA3DJBrJo(aYlRVcR9IXtykBM3QK7TYE3T5nMHUo6OACy)GbdoBPg4P1p8yF)MAv3J68dh1PBZQ)5x(3p`

To reproduce: Have another Paladin in your Group/Raid use Crusader Aura and it will trigger the Icon.

**Comment by Bunny67** [comment]
Correct, since it becomes active and trigger is fired. In the api on the Stance, there is no information about who turned it on. If you need to track your Stance, then I think it is better to use the aura trigger for this.

**Comment by Esstiven** [comment]
Thanks, for the quick response. I will.
