### ISSUE TITLE
Debuff stacking doesn't work

### ISSUE THREAD

**Issue by 3majed** [Bunny67/WeakAuras-WotLK#44]
## Describe the bug
So I want to make Aura that show up sunder armor icon when the target has <=4 stacks and disappear when the target has 5 and show up again when the remaining time for the debuff is <=10.

It used to work without problems on the old weakaura. However here It doesn't count the stacks so it always show up even if the target has more than 4 stacks.

Here is the string. (check legacy arua to see how it was working with the old weakaura)
`!WA:2!nrvZUnsrq4nkcTl(ak4fYHioGYkfexw217QWkerkECSjEv(Xm2jbHwPX9mD5PBspDp0DpX25OpTN9JGVHeN8taYx46OaId7boKNauEaaQEghWwYZut3vx1x9vFDTwRQjvPvPV9Z0JoDWadyp8xO7)GN8UF9NM51kKeDjvRsz6Xl3C)d)N)(h)ZF7VMtKrmLUJIlTHnAEsVM(PBeLzSQKEWi7zPuIfcZkETisPeu1qztAmW84rkz)jwnpog0Mt2rV08TpPMgs2(5pBkjttKKeWSL3x(IxT7njeBedmDzQHNkVXu864Y1s3iZabwmbwE65ergWMx4EqKktAR(Yzo3BiusWWUZ5lfH1GbneeJHDRjleUcK2U4s8rZdAuVBVGU9Q73l9JrNBhlvAO5isKTBkieTPSfdam69kti7MISCAkOjwLE7VEp)LP9w80NGLqhI1cAjBk(DxlsNM(EzsUn0s0XGDMZU5iUXAyZxPsyH4h(qs)zoWww4lkl86rw(vW)H8oAarUF3onp6ip74uW3XE1sF8kSWk4BHBxJRw4uZw5FqOPauipvYl9WiOpSU)XTo7ihDTAT33VSPSOBMKc6pTUorPNGo1WLK(6LLmBIP0FZwp6tEx6gllPa19OyV9MJn6va1TLGyvASO2cpeicll9JK)ptUAyMIPTu7uzoLB(Hmzb3uJiePFiPWUx5(hROWp)G7qXkgcI4Cu4XvYg3DjaP1r4gz9jwUInLi5jol5U(iO02ZZ3XtIINjaXaoYjVEyQgWRcEXA1WfUL7A1Gm2YE4nuKCDhoW1i0gav6uJxcHlX4Kxp3d)3imePRiiV5dZBL)nHd4sUHTY(5hSClSLyiwxib2mSF7dXySnvczapMzbpHIq)dTLiqUQ2M(jzipxXP0cKi)PzHLBTzENkEUI0zO5se4zPo7zuok7JWJnUWhTsaf(uEUxuypWrKkPZ2pYDRzNqdgdbOVOUVF7t9DbYLZivsiX2Vi)fo23ZWVg2j)7NmqaJ4HciVZM5b99hYPwgmtxupfK67JsaE0LJpyjbYMAaXGIPl5V3mhnYTL1oApGhxj0RL5sUCINGF91env71kwOmM1UHKzXbtNMw6F6JVF4JBSutjbrbTV31kvYAEORQ(ZSQORk1dp6Q3SnNM)fZhOrbh2wjwY6(erkJS(DLd8A52Xb5WUn8B28KAzC68xkol0CGO93(5NG0Rlyadheiu6xVo(txYGMDZ3VIh2TTvYF9UAQkar8q2C3ZGsx8CxXNvSqbes38cGCzD3v2VA1lDo1EQGmUnYgP702PQX2e8g33M3upKl42Xbxq0AUshuEYj3te9N6Ma3wIA41QAcR90N)QN(SQx97F3)c`

**Comment by Bunny67** [comment]
Stacks for debuff works.

Example:
```
!WA:2!nr1tVTrru8gfHALfhcoLiuehqPcJQuj06KMgvAKQxxBfJY)yTtccfH9S7(SNHmEMLzM1)jh9bup7pc(gsCYh4mYx46OaN6boKpbO8ba4n76OAl5DFZBFZV37979NLQMVB(O8rV9lUMKyOs1XXgMuOZnXRAaj8YiLmMQgEC72AWS)R3))(3F6V)Z)zkreI2EIKjmbLRCuJk(XReMOnYUnGbMtJJigiij91SqPKhj7lQe1bOksyk(74RneLjNhtWm5cAJV00DurYMD4Y(0PUNnZS1ttL9NKQOTI0fIx7CGCzPefr)Y6jIiq9zLuDLQrgfRthqP)HcQ5IV9rfvq3nE2thtqZf4L1R79IT2DNR7smHuqxhH(yXmD6RsO76bJs0qzzIW0AAQrndDhYV9eNrL5sbOP3I20mcZW2TlZjAn9gDsa0deM6Ok2GPnlxQEJM1BuYVr8hJgxRJqQGkdWmQEmW51IOZAdi6nqYXWIPxN6LJJbfXivB8Q98N72BWBFeg4NqmgqjOJXZ1nyLr3Ylb5UaKg7aMjo5kdyAJMo1fDM5ahGh8HU0jUGnlDTFsGofH8B7zggd(oYP4KS8PbQqTFj)dRE6bXRUadSqSfVYC0BkVt5E75NrVZwSKOMh8VNForbi)4x)KkhCq8kleONr4jqkXUil1AKotqV(d(03nZfOPkyOc)NV7Z35ftXc8cH2nzz2IezQFd2hiCdn(HI3ZLlg9JXmmRNjxb7Q)SDt7xzFi24y3TL9LRB)A7RqOSpUL9j2V0(52c2s5MgX0)yIiTPPirmm(JiPYnYW5qze8R37wCcbDfHFg2yInZLV9saIlHjrOXNGT30XAG3oDsY(bynqtmysAa6eKY8HoPdJbuG1HAapUKe9BkdHJPuX187MGuxoxlrtbMMkAq2NwZEyopNpCctIyypziA6Wu9kjhCcZHzRu52zZAPYmrhLmj2j7h6AVleOrDCqDEjF)Ah7NIo7kOG98rT5WawahShUM97BnrLgXUMipwOueV6Dt)U9cvee0YOw2lAnb)yelBvZ00X66gmTjlh4vvFjtmYJZU6kIks5vfh916LcWB0M1j3Tz7EQ6UJZpb1l7xPYrExjLDxYdxIjBnXid7LX3pO3fBWISBHJtCP6Bwg)5t4XuYY(9zrgkGnmSWlh(ghPJ2tlMWIMUn)0a9B41(2hFeYgoOWnxdMVe83JE99E07(JFzmrW6MEPDS5oZ(epbUByeq0PHLvfeRa0EpKm7pZPgZqq0XqV)1rZ9wt34hcUJm0EDjmbIJvz14Ftqao2fc2E3323oW(Hl8jBYCTUEWyozynhxxOMRxdRKWfUZ6lkfW4mZWMNtukMu1mB0C0DLKwJDLOAcmixkVoO4MpB3nFA(E)139)
```
