### ISSUE TITLE
WEakauras combo bar (rogue)

### ISSUE THREAD

**Issue by shadows9** [Bunny67/WeakAuras-WotLK#45]
## Describe the bug

**Do you have an error log of what happened?**

```
my new weakauras  2.18.0 cause my combo bar config (wa) (rogue)  not working anymore
```

### To Reproduce

**Screenshots**

**Which version of WeakAuras are you using?**

### Additional Info

my new weakauras  2.18.0 cause my combo bar (rogue)  not working anymore

**Comment by Bunny67** [comment]
What exactly does not work for you? Trigger the "Combo Points" works
