### ISSUE TITLE
where is "Smooth Progress"?

### ISSUE THREAD

**Issue by Remberance** [Bunny67/WeakAuras-WotLK#48]
## Describe the bug
in retails wa2, there is Smooth Progress in config.

this options can make energy / mana etc. can increase or reduce smoothly, but in WotLK version, i cant find the options?

**Comment by Bunny67** [comment]
Yes, it is not there, since its implementation takes a lot of resources. There are no plans to add this yet

**Comment by Remberance** [comment]
oh no, what a pity!
