### ISSUE TITLE
Скачки Фреймов

### ISSUE THREAD

**Issue by Merfinx** [Bunny67/WeakAuras-WotLK#5]
При выборе фрейма для Glow Effect, у фрейма изменяется X-Y offset. Такое происходит как в Action, так и в Conditions Tab

**ВНИМАНИЕ!** Такая тенденция замечена только, если Аура находится в группе.

Пруф: https://clips.twitch.tv/LuckyProductiveSlothItsBoshyTime

**Comment by Bunny67** [comment]
Попробую поправить, но пока не понимаю почему они дергаются :)

**Comment by Merfinx** [comment]
Ну, я могу лишь

> Попробую поправить, но пока не понимаю почему они дергаются :)

Скорее всего, когда кликаешь на его, он пытается привязать иконку к положению курсора относительно UI, но не относительно группы как relativeFrame
