### ISSUE TITLE
Can you make "Smooth Progress" back? PLZ

### ISSUE THREAD

**Issue by Remberance** [Bunny67/WeakAuras-WotLK#50]
## Describe the bug
[https://github.com/Bunny67/WeakAuras-WotLK/issues/48]
in this issues, you said its implementation takes a lot of resources. 

but i think you can make option to this module, if someone like, he can select it and have a good game experience, or someone dont like it, close this option and enjoy the game.

PLZ!!!

**Which version of WeakAuras are you using?**
2.18.0

### Additional Info
though this option will take a lot of resources, but when i played feraldudu in game, energy increase per 5 seconds make me feel not good, i cant cast spell in times, so...  Can you make "Smooth Progress" back? OK?    :(

**Comment by Bunny67** [comment]
"Smooth Progress" will not solve the problem with updating the energy

**Comment by Remberance** [comment]
a? why i used original interface, energy will updating smoothly? energy reduce immediatly with casting spell; but increase per 5s.

can you tell me? thx. :)

**Comment by Bunny67** [comment]
WA update energy only when event called. Not update in OnUpdate

**Comment by Remberance** [comment]
how can i solve the problem? i perfer energy increase/reduce immediatly than per 5s. how sad!~

**Comment by Bunny67** [comment]
At the moment I don't know how to fix it

**Comment by Remberance** [comment]
OKOK, thanks very much for your answer! i hope you solve this problem soon ...

**Comment by coolaken** [comment]
用这个可以
function() 
return UnitMana("player"),UnitManaMax("player"),true 
end

**Comment by coolaken** [comment]
!WA:2!1vv3UnXruyw5kOyv1cMsOiHeMirfivIa3skQs9hVo2ytDSdRxtaev2ZUZSENM1ZSD2zD(r9gS6fCTFe819k)euLNGrw9IEDK6lqUR31ZmRJtabrk2ZCM5CMVZ589DSvTcdlGlGFZAttIrID2MILHx9qZ62bbje5ZTMJsLHCr7yjLZsYl2p7G6)v3pR9)eZ)9ziMpC(wCkt6vPAl3QoZnbWHlrAFSIV8BTFtoMyxURB7J9q(7mqWtz4k8iU4jwwwBL7(R9WXsbDWaIi5t)sXILV5QXxonH0BaHreu)oH8DBZ6p)T2EuI5RkCEeMVlSn1JmIWKBjib09C6Sv1MnTtzuPxCeAFIyssmjkQfAiXAMFAIKpSxiftCK0HeSTC)yIxM5to1ykbYI0KLbVtAae8z9QuUJBVoULDChJtfMeTWdMliOOolFfhJhtRWh6HKfBYhO(I4AbPmF9TVZDlMxqKPcwXUag3eXq3z1mGU6D)QtmTjAVZyvksjfZty4IhLbXnw80QBnxxTwMG9hBw2adnWuMbgQvC8dj(74LgJrsIddUws(jA3KcOX0FkM4bjNlK0I6vBUvTUnNKYw0pYhFzea7re3S96M6FEUPuFoRNVPzMd(7yGtqemu0ZGMjaRktqm6qdcx3bkKczn11SzCg5qckH0rkiSbYWlm)KsOPKlsiqyXjJ13rdhvj7Hikd8vvs91xq9nQhQwxvYlGYOjHVR5XEirg)kNLvoiRsGgieEs4zj6VWAk0sDid0S8VBf11MHGlbU2d(hyFfKK9K9scra165zUKBIXM(JvVDC8LoZnwYNZDuMvsuGrHOUy8vmwavfxxj8nAo7YW2JnhaSjc2y81ZZKwVi75So0C(VcnAAW(QZRUMaqS22uZbNw2ZWvaNjJVunb9GIpnfHHmgv019TsKfr(gNB(sp01x7wqhjZ0UCbEBbkE82lwKbIr0eQxeP)IK(mJaM2OvRQo9AwTMB8TwwFGqlGSTxCpT4QxSG4t1eICXx)9CNSfQvofvDOhqU(IYXIQVv8n)qHhVpqMP(HV5kQFiN6hx92m1pzAgQYQlQSvvuB8AvvlvnDru9yvDtvt1q9e1pFJZPAPAR2QV6PZYsfNgpUU77bNStWzjv3RREMLQPAtVqcDqO8M2rCeEDBq05VIZW0ijnVJFekjzf1VK3obYg9IJm8p7iqaR1pLkVXgXxceGLX6MmbtWGCp84S0UMaeO6UJxNkovR26DVjLfovyOVgf7c2RTwr2pJO7cGpvqIVtdTQma5tEvfeqMydSrIx1TX9oD396ODyIroNONjAkcI9oz2)E1(O)Z9F)ChtCdNz(QUj1)EHm7zgBhrp4aKaN9tlvwYoTpGZhAzRfa9Nk5(JYMn8XJE1QumiSzOsPu8SawPg7w)UV8B3(3MfOZDy6aqHZ5SRwB8hFIdkkoeLZdGyaDqEbLPde5eWqXycZPv1Nv1zgxqHbEMbktR32PXlB3YTCZP6Hk0f)QgYmdozD1dYBdtrK5vpk)KtvTNVqIxP1EWJw7(fg93p))d

**Comment by Remberance** [comment]
> 用这个可以
> function()
> return UnitMana("player"),UnitManaMax("player"),true
> end

哈哈，谢谢，这个一会我回去了试一下，是不是要写在％c里？

**Comment by Remberance** [comment]
OKOK, worked!!!!

**Comment by Gabemoon** [comment]
> 用这个可以
> function()
> return UnitMana("player"),UnitManaMax("player"),true
> end

This worked wonderfully. Thanks!
