### ISSUE TITLE
Weakauras Progress Bar Texture + Xperl Textures. 

### ISSUE THREAD

**Issue by Chumanoyasha** [Bunny67/WeakAuras-WotLK#53]
## Describe the bug
 Пытался сменить текстуру прогресс бара на одну из текстур аддона X-Perl. 
После каждого релога, рестарта игры, хотя и остается выбрана текстура X-Perl, текстура сбрасывается на ту, что по-умолчанию. 

### To Reproduce
**1.** Установить Xperl c Curse. Ссылка: https://www.curseforge.com/wow/addons/xperl/files/825399
Моя версия : 
**Title: X-Perl UnitFrames by |cFFFF8080Zek|r
Version: 3.0.9**

**2.** Как показано на моем [видео](https://youtu.be/Tpb4Ib6pwA4) создать Progress bar - сменить текстуру на любую из X-Perl. 
**3.** Прописать /reload или перезайти в игру. 
**4.** Зайти в WeakAuras. 
**5.** Увидите, что текстура сменилась на ту, что стоит по-умолчанию.

**Ссылка на видеозапись по воспроизведению бага:** **[YouTube](https://youtu.be/Tpb4Ib6pwA4)**

З.Ы: С текстурами от Blizzard и/или Weakauras работает как надо.

**Which version of WeakAuras are you using?**
WeakAuras Version: 2.18.0
С предыдущими версиями пробовал, тоже самое.

### Additional Info
Уже кидал ссылку, но не лишним будет думаю, еще разок. 
Ссылка на видео по воспроизведению бага : [YouTube](https://www.youtube.com/watch?v=Tpb4Ib6pwA4)

**Comment by Bunny67** [comment]
Он грузится позже WA, из за этого баг. Есть несколько решение бага, это добавить в WA что бы он грузился позже Xperla(самый не лучший вариант, так как мб ченить другое отвалится), еще вариант тебе самому создать аддон с нужными текстурами и либой LibSharedMedia-3.0, ну и еще 1-н вариант не юзать Xperl или его текстуры  :D 
По другого решения не знаю. Пока закрывать не буду, если устроят решения кроме 1-го, закрой сам.

**Comment by Bunny67** [comment]
Хотя это проблема самого Xperla, он поздно грузит текстуры

**Comment by Chumanoyasha** [comment]
Да, решил вторым способом по этому гайду: https://www.youtube.com/watch?v=5X7NLY37iqY
Изменил так же из Blp формата в Tga мою любимую текстурку из X-Perl через программу BlpLab :)
Спасибо тебе большое за труды Bunny!
