### ISSUE TITLE
Energy (progress) bar not updating smoothly

### ISSUE THREAD

**Issue by Hansrutger** [Bunny67/WeakAuras-WotLK#54]
## Describe the bug
Created a weakaura for my rogue (energy) and my healers (mana) but noticed that it was not updating smoothly. In classic the energy is updated every 20 energy, however in 3.3.5 it's updated smoothly so the weakaura should be updating it the same as well.

### To Reproduce
Video: https://www.youtube.com/watch?v=WOtXH9l3vsk

**Which version of WeakAuras are you using?**
Newest uploaded from your git.

**Comment by Gabemoon** [comment]
Same issue here.

**Comment by Manitary** [comment]
See #50

**Comment by Bunny67** [comment]
fixed in https://github.com/Bunny67/WeakAuras-WotLK/commit/9465daedd86a686a8b74d74531171e96ad99ee54
