### ISSUE TITLE
Есть ли возможность сделать иконки квадратными (в стиле elvui) ?

### ISSUE THREAD

**Issue by gamer4eg** [Bunny67/WeakAuras-WotLK#56]
![image](https://user-images.githubusercontent.com/23147230/99865479-fccae980-2bba-11eb-8493-d070920712db.png)
Собственно есть ли возможность отрубить обводку и срезанные углы?
Если да то прошу пояснения.
Если нет то очень бы хотелось.
Но я понимаю что это далеко не 1 приоритет фиксов.
Заранее спасибо.

**Comment by Bunny67** [comment]
В настойках Отображение, в дополнительных параметрах есть Масштаб, 30% это почти как в елве, так же можно добавить границы как в елве

**Comment by Bunny67** [comment]
Для таких вопросов лучше писать в дискорд

**Comment by gamer4eg** [comment]
![image](https://user-images.githubusercontent.com/23147230/99883069-dbf3aa00-2c35-11eb-83b9-bcb1c29bf919.png)
Помогло, спасибо!
И ок. По вопросам а неб агам буду в дис писать.
