### ISSUE TITLE
Add Model is bugged on Progress Bar

### ISSUE THREAD

**Issue by foxtoopia12** [Bunny67/WeakAuras-WotLK#58]
## Describe the bug
I can't add model to progress bar. It always returns an error whenever I select any of the options available.

**Do you have an error log of what happened?**

```
Date: 2020-12-09 23:40:33
ID: 1
Error occured in: Global
Count: 14
Message: ..\AddOns\WeakAuras\Modernize.lua line 7:
   bad argument #2 to 'format' (string expected, got nil)
Debug:
   WeakAuras\WeakAuras.lua:2502: Add()
   ...ddOns\WeakAurasOptions\OptionsFrames\ModelPicker.lua:157: Pick()
   ...ddOns\WeakAurasOptions\OptionsFrames\ModelPicker.lua:105:
      ...ddOns\WeakAurasOptions\OptionsFrames\ModelPicker.lua:102
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[4]"]:9:
      [string "safecall Dispatcher[4]"]:5
   (tail call): ?
   ...face\AddOns\WeakAuras\Libs\AceGUI-3.0\AceGUI-3.0.lua:318: Fire()
   ...ceGUI-Widgets\AceGUIContainer-WeakAurasTreeGroup.lua:518: SetSelected()
   ...ceGUI-Widgets\AceGUIContainer-WeakAurasTreeGroup.lua:197:
      ...ceGUI-Widgets\AceGUIContainer-WeakAurasTreeGroup.lua:193
```

### To Reproduce

1. Click New Aura
2. Click Progress Bar
2. Click on Add Model
3. Click any model

**Screenshots**

![image](https://user-images.githubusercontent.com/28296117/101659573-cde8ba80-3a78-11eb-9be3-8a303254034d.png)

**Which version of WeakAuras are you using?**

3.0.6

### Additional Info

the aura
https://pastebin.com/qBvdefFY

**Comment by Bunny67** [comment]
This may have already been fixed
