### ISSUE TITLE
Отображаются не все таланты

### ISSUE THREAD

**Issue by Merfinx** [Bunny67/WeakAuras-WotLK#6]
Отображаются не все таланты в Load Section на Talent selected. На остальных классах не смотрел, но паттерн должен быть такой же.

Пруф: https://imgur.com/a/q1rJdUN

**Comment by Bunny67** [comment]
Проверял на последних коммитах? Я таланты уже пытался поправить

**Comment by Merfinx** [comment]
> Проверял на последних коммитах? Я таланты уже пытался поправить

Да, установлена последняя версия

**Comment by Bunny67** [comment]
> Да, установлена последняя версия
Не получается воспроизвести :(

**Comment by Bunny67** [comment]
У меня на локе они не влазят в экран как у тебя
![image](https://user-images.githubusercontent.com/5816685/83891174-72e6ab80-a755-11ea-9eed-619e0b3a00ee.png)
Ну и общее количество у тебя конечно меньше, должно быть 81

**Comment by Merfinx** [comment]
> У меня на локе они не влазят в экран как у тебя
> ![image](https://user-images.githubusercontent.com/5816685/83891174-72e6ab80-a755-11ea-9eed-619e0b3a00ee.png)
> Ну и общее количество у тебя конечно меньше, должно быть 81

После самого последнего обновления пофиксилось. Попробую последить еще за этим. Спасибо :3
