### ISSUE TITLE
Custom Text Display

### ISSUE THREAD

**Issue by Merfinx** [Bunny67/WeakAuras-WotLK#7]
Не отображается custom text через %c.
Проверил документацию по новой версии, должно работать.

Пруф: https://clips.twitch.tv/SavageTameStarlingJebaited

**Comment by Merfinx** [comment]
Перепроверил, с %c1, %c2 работает, но первое возвращающее значение игнорируется

То есть когда я возвращаю
return "1", "2", "3"
при %c1 отображается "2", при %c2 отображается "3", при %c3 не отображается ничего

**Comment by Bunny67** [comment]
Не знаю почему, но там выбирается 2-й аргумент

```
function()
    return 123, 325
end
```
Типо так.

**Comment by Bunny67** [comment]
Из за удаления xpcall, получилась такая беда :)
